---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: xaas
  name: postgres-pvc
  labels:
    app: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: postgres-sc
