---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: xaas
  name: postgres-pv-1
  labels:
    type: local
    app: postgres
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: postgres-sc
  local:
    path: "/mnt/data/postgres"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - worker
