---
apiVersion: v1
kind: Service
metadata:
  name: exposer
  namespace: xaas
  labels:
    app: python
spec:
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30001
  selector:
    app: python
  type: NodePort
